# Generated by Django 5.2.6 on 2025-09-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='auth_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='auth_id_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
